name: ci

on:
  push:
    branches: main

jobs:
  login:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build the hello-docker Docker image
        env:
          SWR_UNAME: ${{ env.SWR_UNAME }}
          SWR_PASSWORD: ${{ env.SWR_PASSWORD }}
        run: |
          docker login -u "$SWR_UNAME" -p "$SWR_PASSWORD" swr.cn-east-3.myhuaweicloud.com
          docker build . --tag swr.cn-east-3.myhuaweicloud.com/esdk-yqz/huaweicloud-demo:latest
          docker run swr.cn-east-3.myhuaweicloud.com/esdk-yqz/huaweicloud-demo:latest
          docker push swr.cn-east-3.myhuaweicloud.com/esdk-yqz/huaweicloud-demo:latest
